### ISSUE TITLE
Using Where step

### ISSUE THREAD

**Issue by sharonjl** [evo-terren/Gremlin.Net.CosmosDb#10]
I am trying to build a query with a Where step, like below:

```
g.V('thomas').outE('knows').where(inV().has('id', 'mary')).drop()
```

How do I go about getting an instance of a traversal source to fulfill `inV().has('id', 'mary')` inside the Where step?

**Comment by evo-terren** [comment]
Gremlin.Net defines a class for anonymous traversals (those that can be defined inside where() and other methods) that is literally called `__`: https://github.com/apache/tinkerpop/blob/master/gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs

Sample usage would be as such:

```c#
using Gremlin.Net.CosmosDb;
using Gremlin.Net.Process.Traversal;

...

using (var graphClient = new GraphClient("Your Gremlin Cosmos Db Host", "Your DB Name", 
			"Your Graph Name", "Your Access Key"))
{
    var g = graphClient.CreateTraversalSource();

    //build the traversal query
    var query = g.V("thomas").OutE("knows").Where(__.InV().Has("id", "Mary")).Drop();

    //execute
    await graphClient.SubmitAsync(query);
}
```

You can also use the `using static` c# feature to hide the usage of `__` as such:

```c#
using static Gremlin.Net.Process.Traversal.__;

...

var query = g.V("thomas").OutE("knows").Where(InV().Has("id", "Mary")).Drop();
```

Read more about this here: http://tinkerpop.apache.org/docs/current/reference/#_static_enums_and_methods_2

I apologize if I screwed up on any of my syntax above - it's not tested or anything.

**Comment by sharonjl** [comment]
Perfect, thank you!

**Comment by sharonjl** [comment]
I was searching GitHub for Gremlin.Net docs for some reason, didn't realize it was merged with Tinkerpop.
