### ISSUE TITLE
Add vertices containing arrays of objects

### ISSUE THREAD

**Issue by davidsblog** [evo-terren/Gremlin.Net.CosmosDb#26]
Hi,

I have a need to store collections/arrays of objects in a Vertex, here's a simple made-up example:

```
[Label("person")]
public class PersonVertex : VertexBase
{
    public int[] Ages { get; set; }
    public string Name { get; set; }
    public IEnumerable<PersonLink> Links { get; set; }
    public PersonPurchasedProductEdge Purchases { get; }
}

public class PersonLink
{
    public int Reference { get; set; }
    public string Name { get; set; }
}
```

...which means that I could create a person object like this:

```
var personV = new PersonVertex
{
    Ages = new[] { 4, 6, 23 },
    Id = "person-12345",
    Label = "some-label",
    Name = "my name",
    Links = new [] { new PersonLink { Name = "ExternalLink", Reference = 1234 } }
};
```

However, if I try to add that to the database, as follows:

```
var test = g.AddV(personV).As("person");
await graphClient.QueryAsync(test);
```

Then I get this `ScriptEvaluationError` exception:

```
ExceptionType : GraphCompileException
ExceptionMessage : Gremlin Query Compilation Error: Script compile error:
Unsupported groovy language rule: 'mapEntry' text: '"Reference":1234'
@ line 1, column 140.
```

I guess that is something else that CosmosDB does not (yet) support?  Would it be possible to do something like that?  Thanks!

**Comment by davidsblog** [comment]
Interestingly, I also tried a two-stage approach.  First create the Vertex **without** the collection:

```
var personV = new PersonVertex
{
    Ages = new[] { 4, 6, 23 },
    Id = "person-12345",
    Label = "some-label",
    Name = "my name"
};
```

...so I'm not setting `Links` this time.  Then I can add it fine:

```
var test = g.AddV(personV).As("person");
await graphClient.QueryAsync(test);
```

...which works perfectly.  Then I tried to **add** the extra "Links" property, like this:

```
var test2 = g.V<PersonVertex>(personV.Id)
   .Property(v => v.Links, new[] {new PersonLink {Name = "Link", Reference = 1234}});
await graphClient.QueryAsync(test2);

```
But it also gives an exception, albeit for a different reason:

```
ExceptionType : GraphCompileException
ExceptionMessage : Gremlin Query Compilation Error: Script compile error: Unexpected token: ':';
in input: 'g.V("person-2345").hasLabel("person").sideEffect(properties("Links").
drop()).property(list,"Links",{"Reference":'. @ line 1, column 113.
```

Any other ideas would be very welcome, many thanks.

**Comment by evo-terren** [comment]
I've almost got something working for your other issue about dollar signs and groovy strings and will address this there as well. There was a bug in how I was serializing object values. More to come soon.

**Comment by davidsblog** [comment]
Awesome!  Thanks, that's amazing.

**Comment by evo-terren** [comment]
The [v0.3.3.2016-alpha](https://github.com/evo-terren/Gremlin.Net.CosmosDb/releases/tag/v0.3.3.2016-alpha) release should address this issue. After re-reading this issue, I didn't ever test object enumerables/arrays specifically, so let me know if I didn't get every case covered. Objects as property values are simply serialized as string property values. I think it should work either way.
