### ISSUE TITLE
Extra quotes appearing in string values

### ISSUE THREAD

**Issue by davidsblog** [evo-terren/Gremlin.Net.CosmosDb#29]
Hi,

Thanks for all your help recently.  I'm just doing some testing.  Since **v0.3.3.2016-alpha**, I am getting some odd results with some string values ... having extra quotes. For example, if I run this example:

```
var personV = new PersonVertex
{
    Ages = new[] { 4, 6, 23 },
    Id = "person-12345",
    Label = "some-label",
    Name = "my name"
};
var test = g.AddV(personV).As("person");
var resp = await graphClient.QueryAsync(test);
```

The code works and the Vertex is created, but I can no longer query for it in the Azure Portal (Data Explorer).  Even if I simply run `g.V()` then it gives this error:

`Failed to execute query: g.V(""person-12345""): Script eval error: 
ExceptionType : GraphCompileException ExceptionMessage :
 Gremlin Query Compilation Error: Script compile error: Unsupported groovy language rule: 'commandExpression' text: 'g.V(""person-12345"")' @ line 1, column 1.
 `

I noticed the extra quotes in that message, so I looked at the data using `g.V().valueMap()` instead, which gives this:

```
[
  {
    "Ages": [
      "4",
      "6",
      "23"
    ],
    "Name": [
      "\"my name\""
    ]
  }
]
```

Which is where I also see extra quotes in the **Name** property.  I'm guessing that's the problem and it's possibly doing the same with the `id` field.

Thanks again for your help.  And sorry about this.

**Comment by davidsblog** [comment]
Yeah, checking the data with a SQL query, the `id` also comes out with extra quotes, like this:

`"id": "\"person-12345\"",`

...which really seems to confuse the Azure Portal!  Nice!

**Comment by evo-terren** [comment]
Well that's embarrassing! That's what I get for not having unit tests, I guess. I'll take a look. Sorry for the hassle!

**Comment by evo-terren** [comment]
New release up. Sorry again! Proceed with caution, I guess.

**Comment by davidsblog** [comment]
No worries, thanks for your help!
