### ISSUE TITLE
Allow the use of text queries

### ISSUE THREAD

**Issue by prapicault** [evo-terren/Gremlin.Net.CosmosDb#3]
I'm exploring with the library and I'm having success, especially with the ability to deserialize content (Thanks!).
However I would like to have the ability to execute queries from text (calling SubmitAsync<T> with the text of the query) rather than using the c# binding to Gremlin.

Is this a contribution that you would accept?

**Comment by evo-terren** [comment]
Is this pull request basically all you would need: #4? Or would you want more than that?

**Comment by prapicault** [comment]
👍 This is what I need and what I had ready in my VS :)

**Comment by evo-terren** [comment]
Looks like the nuget package was just published and verified. You should be good to go: 
`Install-Package Gremlin.Net.CosmosDb -Version 0.3.3.2001-alpha`
