### ISSUE TITLE
Enum write/read inconsistent

### ISSUE THREAD

**Issue by tsteele** [evo-terren/Gremlin.Net.CosmosDb#31]
I tested an enum

public enum Indicator { Red, Green };

set a vertex property with type Indicator to green, then queried the vertex and it returned Red. I assume that it defaults to enum start value as 1.

It would be nice to have the option to store the enum text value in the vertex.

**Comment by evo-terren** [comment]
Hey @tsteele,

Since I'm utilizing Newtonsoft's Json.Net library, you can simply decorate your `Indicator` enum with the `JsonConverter` attribute with the `StringEnumConverter` type like so:

```c#
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace YourNamespace
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Indicator
    {
        Red,
        Green
    }
}
```

Please let me know if this does not satisfy your requirement.

**Comment by tsteele** [comment]
That's great , thanks for the prompt reply.
