### ISSUE TITLE
Can i have sample of code how to use package with grouping

### ISSUE THREAD

**Issue by moumenmosa** [evo-terren/Gremlin.Net.CosmosDb#7]
please can you provide me with samples how to use grouping with your package

**Comment by evo-terren** [comment]
I haven't done anything special with grouping (nor have I actually used it), so I'd recommend checking out the Tinkerpop documentation: http://tinkerpop.apache.org/docs/current/reference/#group-step.

Hope that helps! Let me know if there is anything that is not working as expected when using this code for grouping and I'll address it.
