### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by chriswbarrett** [evo-terren/Gremlin.Net.CosmosDb#9]
I would love to use this project, however I can't find a license anywhere. Could you please include a license?

**Comment by evo-terren** [comment]
Let me get back to you on that. Authoring open source code is something very new to me (and my company). I'll try to figure out which one we're going to use and get it in there.

**Comment by chriswbarrett** [comment]
Awesome, greatly appreciated!

**Comment by evo-terren** [comment]
Okay - sorry that took so long! We had some people go on vacation and it was difficult herding the cats around here. It looks like we ended up settling on the MIT license. I've added it to the repository. I hope that works out for you as well!

**Comment by chriswbarrett** [comment]
That's perfect! Thanks for the quick turnaround
